import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

export const createAssetListStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    header: {
        backgroundColor: colors.surface,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 16,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
        borderBottomWidth: 1,
        borderBottomColor: colors.surface,
    },
    headerContent: {
        marginBottom: 16,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
        marginLeft: 2,
    },
    fab: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        zIndex: 1000,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: colors.text,
        marginLeft: 13,
    },
    headerSubtitle: {
        fontSize: 14,
        color: colors.textSecondary,
        marginLeft: 41,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 48,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 8,
    },
    tableContainer: {
        flex: 1,
        backgroundColor: colors.surface,
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 3,
        marginBottom: 20,
        height: 450,
        borderWidth: 1,
        borderColor: colors.border,
    },
    horizontalScroll: {
        flex: 1,
    },
    tableWrapper: {
        minWidth: 1000,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: colors.background,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        minWidth: 1000,
    },
    headerCell: {
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRightWidth: 1,
        borderRightColor: colors.border,
        justifyContent: 'center',
        minHeight: 50,
    },
    tableBody: {
        // No flex: 1 here, let content determine height
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        minHeight: 70,
        minWidth: 1000,
    },
    cell: {
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRightWidth: 1,
        borderRightColor: colors.border,
        justifyContent: 'center',
        minHeight: 70,
    },
    assetCell: { width: 200 },
    typeCell: { width: 120 },
    statusCell: { width: 140 },
    assignedCell: { width: 180 },
    dateCell: { width: 140 },
    notesCell: { width: 200 },

    assetInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconContainer: {
        width: 40,
        height: 40,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    assetDetails: {
        flex: 1,
    },
    assetName: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 2,
    },
    assetId: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    typeText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        alignSelf: 'flex-start',
    },
    statusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        marginRight: 6,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    assignedText: {
        fontSize: 14,
        color: colors.text,
        fontWeight: '500',
    },
    assignedName: {
        fontSize: 12,
        color: colors.textSecondary,
        marginTop: 2,
    },
    dateText: {
        fontSize: 13,
        color: colors.textSecondary,
    },
    notesText: {
        fontSize: 13,
        color: colors.textSecondary,
        lineHeight: 18,
    },
    viewButton: {
        padding: 8,
        borderRadius: 6,
        backgroundColor: colors.background,
        alignSelf: 'center',
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: colors.surface,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    paginationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: colors.background,
        borderWidth: 1.5,
        borderColor: colors.border,
        gap: 6,
    },
    paginationButtonDisabled: {
        backgroundColor: colors.background,
        borderColor: colors.border,
        opacity: 0.6,
    },
    paginationButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.primary,
    },
    paginationButtonTextDisabled: {
        color: colors.textSecondary,
    },
    pageInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    pageText: {
        fontSize: 14,
        color: colors.textSecondary,
        fontWeight: '500',
    },
    pageNumber: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.primary,
        backgroundColor: colors.background,
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: colors.primary,
    },
    loaderContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    loadingText: {
        fontSize: 16,
        color: colors.textSecondary,
        fontWeight: '500',
    },
    headerText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    dropcontainer: {
        padding: 20,
        backgroundColor: colors.surface,
        borderRadius: 16,
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.border,
    },
    dropdownsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        alignItems: 'center',
    },
    dropdown: {
        flex: 1,
    },
    viewToggleButton: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    viewToggleButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    unassignButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.isDark ? '#7f1d1d30' : '#fef2f2',
        paddingHorizontal: 6,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.isDark ? '#991b1b' : '#fecaca',
        gap: 6,
        alignSelf: 'flex-start',
    },
    unassignText: {
        fontSize: 12,
        color: colors.isDark ? '#f87171' : '#ef4444',
        fontWeight: '600',
    },

    gridContainer: {
        flex: 1,
        backgroundColor: colors.surface,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: 8,
        gap: 12,
    },
    gridCard: {
        width: '100%',
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: colors.border,
        marginTop: -6,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    cardIconContainer: {
        width: 50,
        height: 50,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    cardTitleContainer: {
        flex: 1,
    },
    cardAssetName: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 4,
    },
    cardAssetId: {
        fontSize: 12,
        color: colors.textSecondary,
        fontWeight: '500',
    },
    cardBody: {
        marginBottom: 12,
    },
    cardInfoRow: {
        marginBottom: 10,
    },
    cardInfoText: {
        fontSize: 13,
        color: colors.text,
        lineHeight: 18,
    },
    cardFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingTop: 12,
    },
    cardStatusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
    },
    cardStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 6,
    },
    cardStatusText: {
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    cardRemoveButton: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: colors.isDark ? '#7f1d1d30' : '#fef2f2',
        borderWidth: 1,
        borderColor: colors.isDark ? '#991b1b' : '#fecaca',
    },
    infoIconContainer: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 4,
    },
    infoContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.textSecondary,
        marginRight: 4,
    },
    typeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: colors.border,
    },
    typeIcon: {
        marginRight: 6,
    },
    assignedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: colors.border,
    },
    assignedIcon: {
        marginRight: 6,
    },
    dateContainer: {
        backgroundColor: colors.background,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    descriptionContainer: {
        backgroundColor: colors.background,
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
    },
    descriptionText: {
        fontSize: 13,
        color: colors.textSecondary,
        lineHeight: 18,
    },
    moreButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-end',
        marginTop: 8,
        gap: 4,
    },
    moreText: {
        fontSize: 12,
        color: colors.primary,
        fontWeight: '600',
    },
    Emptycontainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        marginVertical: 20,
    },
    Emptymessage: {
        fontSize: 16,
        color: colors.textSecondary,
        fontStyle: 'italic',
        textAlign: 'center',
    },
});

export const assetListStyles = createAssetListStyles({
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#1f2937',
    textSecondary: '#6b7280',
    primary: '#3b82f6',
    border: '#e5e7eb',
    isDark: false,
});