import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f4f6fa' },

  header: {
    backgroundColor: '#007bff',
    height: 110,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 60,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  headerIcon: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    padding: 8,
    borderRadius: 30,
  },

  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 25,
    width: '85%',
    alignSelf: 'center',
    marginTop: -40,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 6,
    elevation: 4,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#007bff',
  },
  name: {
    fontSize: 22,
    fontWeight: '800',
    marginTop: 12,
    color: '#222',
  },
  email: { fontSize: 15, color: '#666', marginBottom: 10 },
  editProfileBtn: {
    flexDirection: 'row',
    backgroundColor: '#e8f0fe',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
    alignItems: 'center',
    marginTop: 8,
  },
  editProfileText: {
    color: '#007bff',
    fontWeight: '600',
    marginLeft: 6,
  },

  cardContainer: { paddingHorizontal: 20, paddingTop: 25 },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '700',
    marginVertical: 12,
    color: '#333',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  row: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  infoText: { marginLeft: 10, fontSize: 16, color: '#555' },

  logoutButton: {
    backgroundColor: '#dc3545',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    paddingVertical: 12,
    marginTop: 10,
    marginBottom: 30,
  },
  logoutText: { color: '#fff', fontWeight: '700', fontSize: 16, marginLeft: 6 },
});
